name: gazebo5_import
method: http://packages.osrfoundation.org/gazebo/ubuntu
suites: [trusty, utopic]
component: main
architectures: [i386, amd64, source]
filter_formula: Package (% libsdformat2) | Package (% libsdformat2-dbg) | Package (% libsdformat2-dev) | Package (% sdformat-sdf) | Package (% libsimbody3.5) | Package (% libsimbody3.5-dbg) | Package (% libsimbody-dev)
